# Generated by Django 2.1 on 2018-08-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('projectid', models.CharField(max_length=255, verbose_name='Проект')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка')),
                ('featureimg', models.CharField(blank=True, max_length=255, null=True, verbose_name='featureimg')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='alias')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата создания')),
                ('sort', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер очередности в списке страниц')),
                ('published', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес страницы')),
                ('filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла')),
                ('html', models.TextField(default='', verbose_name='HTML')),
                ('page_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес страницы на сервере')),
                ('iframe', models.TextField(default='', verbose_name='IFrame code')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('customdomain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Домен')),
                ('export_csspath', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь экспорта')),
                ('export_jspath', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь экспорта')),
                ('export_imgpath', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь экспорта')),
                ('indexpageid', models.CharField(blank=True, max_length=255, null=True, verbose_name='indexpageid')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('ProjectPages', models.ManyToManyField(blank=True, to='export_app.Page')),
            ],
        ),
        migrations.CreateModel(
            name='StaticFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('path', models.CharField(max_length=255, verbose_name='Путь у нас')),
                ('path_tilda', models.CharField(max_length=255, verbose_name='Путь у них')),
            ],
        ),
        migrations.CreateModel(
            name='TildaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('request_count', models.IntegerField(default=0, verbose_name='Количество запросов за час')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='static_files',
            field=models.ManyToManyField(blank=True, to='export_app.StaticFile'),
        ),
        migrations.AddField(
            model_name='page',
            name='static_files',
            field=models.ManyToManyField(blank=True, to='export_app.StaticFile'),
        ),
    ]
