# Generated by Django 2.1 on 2018-08-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='page',
            name='descr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='featureimg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='featureimg'),
        ),
        migrations.AlterField(
            model_name='page',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='page',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sort',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер очередности в списке страниц'),
        ),
    ]
