# Generated by Django 2.1 on 2018-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0003_auto_20180811_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='tildarequest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
    ]
