# Generated by Django 3.1 on 2024-02-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0003_auto_20180903_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='children_objects_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
