# Generated by Django 3.1 on 2024-02-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0004_project_children_objects_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='children_objects_count',
            field=models.IntegerField(null=True),
        ),
    ]
