# Generated by Django 2.1 on 2018-08-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0004_tildarequest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='project',
            name='page404id',
        ),
        migrations.AddField(
            model_name='page',
            name='page_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес страницы на сервере'),
        ),
    ]
