# Generated by Django 3.1 on 2024-02-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0005_auto_20240222_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationTaskProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор таски')),
                ('project_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор проекта')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='children_objects_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
