# Generated by Django 2.1 on 2018-08-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0005_auto_20180813_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='iframe',
            field=models.TextField(default='', verbose_name='IFrame code'),
        ),
    ]
