# Generated by Django 3.1 on 2024-02-28 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0006_auto_20240228_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtaskproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
