# Generated by Django 3.1 on 2024-02-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0007_relationtaskproject_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='children_objects_count',
            new_name='total_objects',
        ),
        migrations.AddField(
            model_name='project',
            name='objects_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
