# Generated by Django 2.1 on 2018-08-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0007_auto_20180815_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='page',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
