# Generated by Django 3.1 on 2024-03-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0008_auto_20240229_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='objects_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
